### ISSUE TITLE
Connecting reviews service to view

### ISSUE THREAD

**Issue by Elias-Llera** [Arquisoft/lomap_en1b#101]
Both the service and the view are implemented, we need to put them together

**Comment by MarioP-Dev** [comment]
We cannot use the fetch API on ReviewsService to transform base64 images into blob images as the NodeJS version required to use the inrupt solid package is v16 and the Fetch API is in experimental version on v18

**Comment by Elias-Llera** [comment]
In order to solve the issue, we are going to store the image as a different RDF rerource in the pod, not as a file. That way the RDF resource will have the encoded image and will be decoded only in the client.
