### ISSUE TITLE
Adding names and emails to documentation

### ISSUE THREAD

**Issue by Elias-Llera** [Arquisoft/lomap_en1b#4]
Every team member  should add his/her name and email into a new section at the end of the README and merge it into develop branch via pull requests.

When the README is finished, it should be pushed into master.

**Comment by MarioP-Dev** [comment]
Names "Sara María Ramírez Pérez" and "Mario Pérez Fernández" added to README.md file

**Comment by UO276188** [comment]
Pull requests already closed: #1 and #3.

**Comment by Elias-Llera** [comment]
All names have been added to the readme and pushed to master
