### ISSUE TITLE
Implementing the login with SOLID PODs

### ISSUE THREAD

**Issue by Elias-Llera** [Arquisoft/lomap_en1b#48]
We need to implement the application login, using the SOLID PODs. It is going to be placed in the WebApp. 

We need the GUI for the login and the comunication with the POD.

Remember that the library that we are using for the UI is Chackra 
https://chakra-ui.com/

**Comment by MarioP-Dev** [comment]
We must install the CORS dependence to allow cross-origin requests

**Comment by Elias-Llera** [comment]
We ended up deciding the login process was going to work thorugh the server and not the WebApp. We had a small talk about it in [this Solid Forums topic](https://forum.solidproject.org/t/how-to-authenticate-a-restapi-to-write-on-a-user-pod/6295).

The login service up and running, we need to review the providers URL in thew WebAPP and maybe extract them to an enum or something
