### ISSUE TITLE
Map view in the webapp

### ISSUE THREAD

**Issue by Elias-Llera** [Arquisoft/lomap_en1b#49]
The main view of the webapp will be a Map. We need to implement the first version with React, just a screen with a map in the center. No need to add markers yet.

For now, let´s try using leaflet.
https://leafletjs.com/

Remember that the library that we are using for the UI is Chackra 
https://chakra-ui.com/

**Comment by UO276188** [comment]
#55

**Comment by Elias-Llera** [comment]
Map already working with markers, we need to start implementing navigation menus and titles in the view
