### ISSUE TITLE
Logout access from the WebAPP

### ISSUE THREAD

**Issue by Elias-Llera** [Arquisoft/lomap_en1b#68]
We need to offer the view acccess to the logout functionality of the server.

**Comment by MarioP-Dev** [comment]
Due to an error on the PODS access on non-existent collection, I cannot correctly test the functionality.
Another developer should test that the functionality is working until this error is fixed
@Elias-Llera @uo276670

**Comment by MarioP-Dev** [comment]
Logout was tested by @UO276188 and it's currently working
